# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerdns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cryptokey',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='domainmetadata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='supermaster',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tsigkey',
            options={'managed': False},
        ),
    ]
