# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 08:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('penatesserver', '0005_auto_20151226_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('dn', models.CharField(max_length=200)),
                ('fqdn', ldapdb.models.fields.CharField(db_column='uid', max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z][\\w_\\-]{0,199}$')])),
                ('uid_number', ldapdb.models.fields.IntegerField(db_column='uidNumber', default=None, unique=True)),
                ('gid_number', ldapdb.models.fields.IntegerField(db_column='gidNumber', default=None)),
                ('display_name', ldapdb.models.fields.CharField(db_column='displayName', max_length=200)),
                ('mail', ldapdb.models.fields.CharField(db_column='mail', default=None, max_length=200)),
                ('gecos', ldapdb.models.fields.CharField(db_column='gecos', default=None, max_length=200)),
                ('cn', ldapdb.models.fields.CharField(db_column='cn', default=None, max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z][\\w_\\-]{0,199}$')])),
                ('sn', ldapdb.models.fields.CharField(db_column='sn', default=None, max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z][\\w_\\-]{0,199}$')])),
                ('user_password', ldapdb.models.fields.CharField(db_column='userPassword', default=None, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=ldapdb.models.fields.CharField(db_column='cn', max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z][\\w_\\-]{0,199}$')]),
        ),
        migrations.AlterField(
            model_name='groupofnames',
            name='name',
            field=ldapdb.models.fields.CharField(db_column='cn', max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z][\\w_\\-]{0,199}$')]),
        ),
        migrations.AlterField(
            model_name='host',
            name='fqdn',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='hostname.infra.domain', max_length=255, null=True, verbose_name='Host fqdn'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cn',
            field=ldapdb.models.fields.CharField(db_column='cn', default=None, max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z][\\w_\\-]{0,199}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=ldapdb.models.fields.CharField(db_column='uid', max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z][\\w_\\-]{0,199}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='sn',
            field=ldapdb.models.fields.CharField(db_column='sn', default=None, max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z][\\w_\\-]{0,199}$')]),
        ),
    ]
